default_context:
  project_name: 'mie-fastapi'
  project_slug: 'mie-fastapi'
  domain_main: 'mie-main.com'
  domain_staging: 'stag.mie-main.com'
  docker_swarm_stack_name_main: 'mie-main-com'
  docker_swarm_stack_name_staging: 'stag-mie-main-com'
  secret_key: '3058b8dd8ba0f0278547cde864aa7203c3886ea8776fd428c1a1425358519f0b'
  first_superuser: 'mie-superuser@mie-main.com'
  first_superuser_password: '3058b8dd8ba0f0278547cde864aa7203c3886ea8776fd428c1a1425358519f0b'
  backend_cors_origins: '[["http://dev.mie-main.com"]]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@mie-main.com'
  postgres_password: 'a0ce2fb21b103f03d0a8eb5261e1e28eccb58a7d0eeaa9e4a94ca40bae0bdf7c'
  pgadmin_default_user: 'mie-pgsuperuser@mie-main.com'
  pgadmin_default_user_password: 'a0ce2fb21b103f03d0a8eb5261e1e28eccb58a7d0eeaa9e4a94ca40bae0bdf7c'
  traefik_constraint_tag: 'mie-main.com'
  traefik_constraint_tag_staging: 'stag.mie-main.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:3058b8dd8ba0f0278547cde864aa7203c3886ea8776fd428c1a1425358519f0b'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'mie-main_backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
